### ISSUE TITLE
Crashed while typing text

### ISSUE THREAD

**Issue by wenkeming** [ChimeHQ/Chime#21]
Process:               Chime [19851]
Path:                  /Applications/Chime.app/Contents/MacOS/Chime
Identifier:            com.chimehq.Edit
Version:               3.0.0 (203)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024/10/27 10:31:12.0933
OS Version:            macOS 14.7 (23H124)
Report Version:        12
Anonymous UUID:        002148F1-8E7A-F804-B811-3B31ED260075

Time Awake Since Boot: 8100 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001a1511f28

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [19851]

**Comment by mattmassicotte** [comment]
Thanks so much for reporting this! I'm afraid this version of Chime, as an editor, is non-functional at the moment. This version is really only usable as a QuickLook preview system. 😞

However! I'm hoping to make more progress on the actual core editing functionality soon. There's a tremendous amount of work to do, but at least getting it to a working state would be pretty nice.

Sorry for wasting your time here!
