### ISSUE TITLE
Status bar style

### ISSUE THREAD

**Issue by mattmassicotte** [ChimeHQ/Chime#5]
The status bar was an area that was problematic. It was entirely implemented in AppKit, and integrated closely with theming. There's now a new system, implemented in the "Status" module. However, it is both non-functional also very poorly styled.

It would be great to get it looking nicer!

**Comment by mattmassicotte** [comment]
👋🏻 @unnamedd

But, just remember, there is **no pressure** at all. I'll make sure to update this ticket if I end up touching anything close.

**Comment by unnamedd** [comment]
@mattmassicotte may you assign this ticket to me?

**Comment by mattmassicotte** [comment]
Of course!

One of the big challenges here is the theming system (`Theme` module) is being re-implemented. It will not have enough to make general theming possible. But there should be enough infrastructure to make it possible to do.

**Comment by mattmassicotte** [comment]
The current UI has all kinds of placeholders for various components. The blue bar at the bottom is a placeholder for the search system. The status bar is only the green-colored elements that float over the editor view.

**Comment by mattmassicotte** [comment]
Just looking more closely at it now, I think a good first goal would be to enforce some minimum sizing so that the item don't get squished if the view is too small.

**Comment by mattmassicotte** [comment]
I'm calling this as good enough for now. It's much improved.
